project:
  type: website

website:
  title: "EVE 113 R Bootcamp"
  navbar:
    left:
      - href: Home.qmd
        text: Home
      - href: About.qmd
        text: About
      - href: Tutorial 0.qmd
        text: Tutorial 0

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual