project:
  type: website

website:
  title: "CMM R Bootcamp"
  navbar:
    left:
      - href: Home.qmd
        text: Home
      - About.qmd
      - Tutorial 1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

